version: 1.0.4-{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore
init:
- ps: Set-WinSystemLocale ru-RU
- ps: Start-Sleep -s 5
- ps: Restart-Computer
install:
- cmd: >-
    choco install onescript.cli -source https://www.myget.org/F/onescript -y
    
    refreshenv
    
    opm install opm
    
configuration: Release
build:
  verbosity: minimal
test_script:
- ps: nunit3-console --x86 NUnitTests\bin\Debug\NUnitTests.dll

after_build:
- cmd: >-
    copy MailComponent/bin/Release/*.dll lib/
    
    del lib/ScriptEngine*.dll
    
    cd lib
    
    opm build .
    
    cd ..
    
artifacts:
- path: lib\*.ospx
  name: InternetMail
- path: lib\*.dll
  name: components